# Generated by Django 5.2.3 on 2025-07-11 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='存储条目详细内容的文本字段', verbose_name='条目内容')),
                ('image', models.ImageField(blank=True, help_text='可选：上传与条目相关的图片', null=True, upload_to='entry_images/%Y/%m/%d/', verbose_name='条目图片')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '私有')], default='private', help_text='设置该条目的可见性', max_length=10, verbose_name='可见性')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to=settings.AUTH_USER_MODEL, verbose_name='条目作者')),
            ],
            options={
                'verbose_name': '条目',
                'verbose_name_plural': '条目',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='评论内容最大长度为500字符', max_length=500, verbose_name='评论内容')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='learning_logs.entry', verbose_name='被评论条目')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='主题名称最大长度为200个字符', max_length=200, verbose_name='主题名称')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('visibility', models.CharField(choices=[('public', '公开'), ('private', '私有')], default='private', help_text='设置该主题的可见性', max_length=10, verbose_name='可见性')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '主题',
                'verbose_name_plural': '主题',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='learning_logs.topic', verbose_name='关联主题'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='learning_logs.entry', verbose_name='被点赞条目')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='点赞用户')),
            ],
            options={
                'verbose_name': '点赞',
                'verbose_name_plural': '点赞',
                'unique_together': {('user', 'entry')},
            },
        ),
    ]
