# Generated by Django 5.2.3 on 2025-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='visibility',
        ),
        migrations.AddField(
            model_name='topic',
            name='is_public',
            field=models.BooleanField(default=False, help_text='勾选后该主题可通过链接分享给他人', verbose_name='是否公开'),
        ),
        migrations.AddField(
            model_name='topic',
            name='share_expire_at',
            field=models.DateTimeField(blank=True, help_text='可选：设置分享过期时间，为空则永久有效', null=True, verbose_name='过期时间'),
        ),
        migrations.AddField(
            model_name='topic',
            name='share_password',
            field=models.CharField(blank=True, help_text='可选：设置访问密码，为空则无需密码', max_length=50, null=True, verbose_name='访问密码'),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
